export default interface IEventRequest {
<<<<<<< HEAD
    event_id: String,
    event_type: String,
    type: String,
    title: String,
    remarks: String,
    start_date: String,
    end_date: String,
    start_time: String,
    end_time: String,
    no_participants: Number,
    budget: Number,
    project: String,
    vote: String,
    location: String,
    venue_name: String,
    venue_type: String,
    fund_type: String,
=======
    eventId: string,
    eventType: string,
    type: string,
    title: string,
    remarks: string,
    startDate: string,
    endDate: string,
    startTime: string,
    endTime: string,
    noParticipants: number,
    budget: number,
    project: string,
    vote: string,
    location: string,
    venueName: string,
    venueType: string,
    fundType: string,
>>>>>>> fd3210359d6c143215aef639c14815d77d7d10c7
    

  }