export enum RequestStatus {
	SUCCESS = 'SUCCESS',
	ERROR = 'ERROR',
	CHANGE_PASSWORD = 'CHANGE_PASSWORD',
	UNAUTHORIZED = 'UNAUTHORIZED',
	PENDING = 'PENDING',
	APPROVED = 'APPROVED',
	DISAPPROVED = 'DISAPPROVED',
}
